name: fuckoff
version: stable
version-script: git -C parts/fuckoff/build describe --abbrev=0 --tags
summary: A fork/rewrite of the excellent nvbn/thefuck
description: |
  Fuckoff tries to match a rule for the previous command,
  creates a new command using the matched rule and runs it.

grade: stable
confinement: classic

apps:
  fuckoff:
    command: bin/fuckoff
  fuck:
    command: bin/fuck

parts:
  fuckoff:
    source: https://github.com/cyuria/fuckoff.git
    plugin: python
