name: Tests

on: [push, pull_request]

env:
  PYTHON_LATEST: "3.11"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.pythonLocation }}/bin/*
            ${{ env.pythonLocation }}/lib/*
            ${{ env.pythonLocation }}/scripts/*
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('setup.py', 'requirements.txt') }}

      - name: Install Fuckoff with all dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          pip install -Ur requirements.txt coveralls
          python setup.py develop

      - name: Lint
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == env.PYTHON_LATEST
        run: flake8

      - name: Run tests
        if: matrix.os != 'ubuntu-latest' || matrix.python-version != env.PYTHON_LATEST
        run: coverage run --source=fuckoff,tests -m pytest -v --capture=sys tests
      - name: Run tests (including functional)
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == env.PYTHON_LATEST
        run: |
          docker build -t fuckoff/python3 -f tests/Dockerfile --build-arg PYTHON_VERSION=3 .
          coverage run --source=fuckoff,tests -m pytest -v --capture=sys tests --enable-functional
      - name: Post coverage results
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == env.PYTHON_LATEST
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls --service=github
